;; Context

;; cairo_fill_rule_t
(define CAIRO_FILL_RULE_WINDING 0)
(define CAIRO_FILL_RULE_EVEN_ODD 1)

;; cairo_line_cap_t
(define CAIRO_LINE_CAP_BUTT 0)
(define CAIRO_LINE_CAP_ROUND 1)
(define CAIRO_LINE_CAP_SQUARE 2)

;; cairo_line_join_t
(define CAIRO_LINE_JOIN_MITER 0)
(define CAIRO_LINE_JOIN_ROUND 1)
(define CAIRO_LINE_JOIN_BEVEL 2)


;; cairo_operator_t
(define CAIRO_OPERATOR_CLEAR 0)

(define CAIRO_OPERATOR_SOURCE 1)
(define CAIRO_OPERATOR_OVER 2)
(define CAIRO_OPERATOR_IN 3)
(define CAIRO_OPERATOR_OUT 4)
(define CAIRO_OPERATOR_ATOP 5)

(define CAIRO_OPERATOR_DEST 6)
(define CAIRO_OPERATOR_DEST_OVER 7)
(define CAIRO_OPERATOR_DEST_IN 8)
(define CAIRO_OPERATOR_DEST_OUT 9)
(define CAIRO_OPERATOR_DEST_ATOP 10)

(define CAIRO_OPERATOR_XOR 11)
(define CAIRO_OPERATOR_ADD 12)
(define CAIRO_OPERATOR_SATURATE 13)

