;; cairo_content_t
(define CAIRO_CONTENT_COLOR #x1000)
(define CAIRO_CONTENT_ALPHA #x2000)
(define CAIRO_CONTENT_COLOR_ALPHA #x3000)

;; cairo_surface_type_t
(define CAIRO_SURFACE_TYPE_IMAGE 0)
(define CAIRO_SURFACE_TYPE_PDF 1)
(define CAIRO_SURFACE_TYPE_PS 2)
(define CAIRO_SURFACE_TYPE_XLIB 3)
(define CAIRO_SURFACE_TYPE_XCB 4)
(define CAIRO_SURFACE_TYPE_GLITZ 5)
(define CAIRO_SURFACE_TYPE_QUARTZ 6)
(define CAIRO_SURFACE_TYPE_WIN32 7)
(define CAIRO_SURFACE_TYPE_BEOS 8)
(define CAIRO_SURFACE_TYPE_DIRECTFB 9)
(define CAIRO_SURFACE_TYPE_SVG 10)
(define CAIRO_SURFACE_TYPE_OS2 11)
(define CAIRO_SURFACE_TYPE_WIN32_PRINTING 12)
(define CAIRO_SURFACE_TYPE_QUARTZ_IMAGE 13)

